### ISSUE TITLE
Melhoria no metodo observer do rast-pvi.js

### ISSUE THREAD

**Issue by thiagosantosinova** [libs-scripts-mep/rast-pvi#1]
Desenvolver uma melhoria que possibilite a utilização de qualquer nome para o sessionStorage referente ao SerialNumber. Hoje da maneira que esta estruturado temos que obrigatoriamente utilizar o nome 'SerialNumber' no sessionStorage definido no main.

```js
    static Observer(message, param) {

        if (message.includes("rastreamento.init")) {

            let ns = message.match(/[1][0]{4}[0-9]{8}/)

            if (sessionStorage.getItem("SerialNumber") == ns) {

                sessionStorage.setItem("RastInit", JSON.stringify(param))

            }
        }

        if (message.includes("rastreamento.end")) {

            let ns = message.match(/[1][0]{4}[0-9]{8}/)

            if (sessionStorage.getItem("SerialNumber") == ns) {

                sessionStorage.setItem("RastEnd", JSON.stringify(param))

            }
        }
    }

```

**Comment by inv-lucasgkroth** [comment]
A partir da versão 2.0.0 o rastreamento é tratado como uma instância de uma classe, contendo o número de série, e informações de inicialização, e finalização do rastreamento na própria instância, não se fazendo mais necessário a implementação dessa issue.
